/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DatabaseService_constants.h"

namespace nanolat { namespace thrift {

const DatabaseServiceConstants g_DatabaseService_constants;

DatabaseServiceConstants::DatabaseServiceConstants() {
  PROTOCOL_VERSION = 1;

}

}} // namespace

