/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LeaderboardService_CONSTANTS_H
#define LeaderboardService_CONSTANTS_H

#include "LeaderboardService_types.h"

namespace nanolat { namespace leaderboard {

class LeaderboardServiceConstants {
 public:
  LeaderboardServiceConstants();

  int32_t PROTOCOL_VERSION;
};

extern const LeaderboardServiceConstants g_LeaderboardService_constants;

}} // namespace

#endif
