// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "database.h"
#include "leaderboard.h"

void print_usage()
{
	printf("cpp_sync <database/leaderboard> <server address> <port>\n");
}


int main(int argc, const char **argv) {

	if (argc != 4)
	{
		print_usage();
		return -1;
	}

	const char * service = argv[1];
	const char * address = argv[2];
	int port = atoi(argv[3]);

	if ( strcasecmp(service, "database")  == 0 ) {
		return database_client(address, port);
	} else if ( strcasecmp(service, "leaderboard") == 0 ) {
		return leaderboard_client(address, port);
	} else {
		print_usage();
		return -1;
	}

	return 0;
}
