// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <nanolat/server.h>
#include <stdio.h>
#include <stdlib.h>

void print_usage()
{
	printf("nanolat <listen-port>\n");
}

int main(int argc, char **argv) {
  int port = 9090;

  if (argc >= 2)
  {
	  port = atoi(argv[1]);

	  if (port == 0) {
		  printf("Invalid Port.\n");
		  print_usage();
		  return -1;
	  }
  }

  printf("Nanolat Server : Listening to port %d\n", port);

  nanolat::leaderboard::listen(port);

  return 0;
}
