/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DatabaseService_CONSTANTS_H
#define DatabaseService_CONSTANTS_H

#include "DatabaseService_types.h"

namespace nanolat { namespace thrift {

class DatabaseServiceConstants {
 public:
  DatabaseServiceConstants();

};

extern const DatabaseServiceConstants g_DatabaseService_constants;

}} // namespace

#endif
