/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LeaderboardService_constants.h"

namespace nanolat { namespace leaderboard {

const LeaderboardServiceConstants g_LeaderboardService_constants;

LeaderboardServiceConstants::LeaderboardServiceConstants() {
  PROTOCOL_VERSION = 1;

}

}} // namespace

