// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <nanolat/server.h>

int main(int argc, char **argv) {
  int port = 9090;

  nanolat::server::listen(port);

  return 0;
}

